"""CPU-only model loading and inference for showcase games."""
from __future__ import annotations

import json
import logging
import os
import threading
from collections import OrderedDict
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn

from keisei.training.model_registry import build_model, get_model_contract, get_obs_channels
from keisei.training.models.katago_base import KataGoBaseModel

logger = logging.getLogger(__name__)


def enforce_cpu_only(cpu_threads: int = 2) -> None:
    """Set environment and torch config for CPU-only inference.
    MUST be called before any other torch operations in the process.
    """
    os.environ["CUDA_VISIBLE_DEVICES"] = ""
    torch.set_num_threads(cpu_threads)
    try:
        torch.set_num_interop_threads(1)
    except RuntimeError:
        pass  # already set — safe to ignore in tests


def load_model_for_showcase(
    checkpoint_path: Path | str,
    architecture: str,
    model_params: dict[str, Any],
) -> nn.Module:
    """Load a model checkpoint for CPU-only showcase inference.
    Raises FileNotFoundError if checkpoint doesn't exist.
    """
    path = Path(checkpoint_path)
    if not path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {path}")

    model = build_model(architecture, model_params)
    state_dict = torch.load(path, map_location="cpu", weights_only=True)
    model.load_state_dict(state_dict, strict=True)
    model.eval()

    if isinstance(model, KataGoBaseModel):
        model.configure_amp(enabled=False)

    for name, param in model.named_parameters():
        assert param.device == torch.device("cpu"), (
            f"Parameter {name} on {param.device} — GPU leak in showcase"
        )

    return model


def run_inference(
    model: nn.Module,
    obs: np.ndarray,
    architecture: str,
) -> tuple[np.ndarray, float]:
    """Run a single forward pass. Returns (policy_logits, win_probability).

    Requires the complete observation contract generated by SpectatorEnv.

    win_probability normalized to [0, 1]:
    - scalar contract: tanh [-1,1] -> [0,1]
    - multi_head contract: softmax(value_logits)[0] = P(win)
    """
    policy, legacy_value, _ = run_inference_with_evaluation(
        model, obs, architecture, player="black", position_ply=0,
    )
    return policy, legacy_value


def run_inference_with_evaluation(
    model: nn.Module,
    obs: np.ndarray,
    architecture: str,
    *,
    player: str,
    position_ply: int,
) -> tuple[np.ndarray, float, dict[str, Any]]:
    """Infer once, retaining legacy value and a qualified pre-move outcome score.

    Outcome score gives a draw half credit. It is an uncalibrated model
    estimate from ``player``'s perspective, not a probability of winning.
    """
    if player not in {"black", "white"}:
        raise ValueError("Evaluated player must be black or white")
    if type(position_ply) is not int or position_ply < 0:
        raise ValueError("Evaluated position ply must be a nonnegative integer")
    expected_channels = get_obs_channels(architecture)
    if obs.shape != (expected_channels, 9, 9):
        raise ValueError(
            f"Expected observation shape {(expected_channels, 9, 9)}, got {obs.shape}"
        )
    if not np.isfinite(obs).all():
        raise ValueError("Non-finite observation")

    obs_tensor = torch.from_numpy(obs).unsqueeze(0).float()

    with torch.inference_mode():
        output = model(obs_tensor)

    contract = get_model_contract(architecture)

    evaluation: dict[str, Any] = {
        "version": 1, "kind": "outcome_score", "player": player,
        "position_ply": position_ply,
        "source": {"architecture": architecture, "contract": contract},
    }
    if contract == "multi_head":
        # NOTE: reshape(-1) flattens (9,9,139) in row-major order.
        # This matches the SpatialActionMapper's flat index convention
        # used by SpectatorEnv(action_mode="spatial").
        policy_logits = output.policy_logits.squeeze(0).reshape(-1)
        wdl = torch.softmax(output.value_logits.squeeze(0), dim=0)
        if wdl.shape != (3,) or not torch.isfinite(wdl).all():
            raise ValueError("Invalid W/D/L model output")
        win_prob = wdl[0].item()
        score = win_prob + 0.5 * wdl[1].item()
        evaluation["wdl"] = dict(zip(("win", "draw", "loss"), wdl.tolist(), strict=True))
    else:
        policy_logits_t, value_tensor = output
        policy_logits = policy_logits_t.squeeze(0)
        win_prob = (value_tensor.squeeze(0).item() + 1.0) / 2.0
        score = win_prob

    if not torch.isfinite(policy_logits).all() or not np.isfinite(win_prob):
        raise ValueError("Non-finite model output")
    if not 0.0 <= score <= 1.0:
        raise ValueError("Outcome score outside [0, 1]")
    evaluation["score"] = float(score)
    return policy_logits.numpy(), float(win_prob), evaluation


class ModelCache:
    """LRU cache invalidated when checkpoint contents or model configuration change.

    Thread-safe: all access is guarded by a lock.
    """

    def __init__(self, max_size: int = 2) -> None:
        self._cache: OrderedDict[tuple[Any, ...], nn.Module] = OrderedDict()
        self._max_size = max_size
        self._lock = threading.Lock()

    @property
    def size(self) -> int:
        with self._lock:
            return len(self._cache)

    def get_or_load(
        self,
        entry_id: str,
        checkpoint_path: str,
        architecture: str,
        model_params: dict[str, Any],
    ) -> nn.Module:
        path = Path(checkpoint_path).resolve()
        stat = path.stat()
        key = (
            entry_id, str(path), stat.st_dev, stat.st_ino, stat.st_size,
            stat.st_mtime_ns, stat.st_ctime_ns, architecture,
            json.dumps(model_params, sort_keys=True),
        )
        with self._lock:
            if key in self._cache:
                self._cache.move_to_end(key)
                return self._cache[key]

        # Load outside the lock (slow I/O)
        model = load_model_for_showcase(checkpoint_path, architecture, model_params)

        with self._lock:
            # Check again — another thread may have loaded it
            if key in self._cache:
                return self._cache[key]
            # A replaced checkpoint supersedes previous generations for this entry.
            for old_key in list(self._cache):
                if old_key[:2] == key[:2]:
                    del self._cache[old_key]
            self._cache[key] = model
            while len(self._cache) > self._max_size:
                evicted_key, _ = self._cache.popitem(last=False)
                logger.debug("Evicted model %s from cache", evicted_key)
        return model
